name: ci

on:
  push:
    paths-ignore:
    - 'changelog.md'
    - 'license.md'
    - 'readme.md'
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Install .NET 7.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
          6.0.x
          7.0.x
        include-prerelease: true

    - name: Build, Test (Debug & Release), Publish (main only)
      shell: bash
      working-directory: ./src/BadIdeas.Icons.FontAwesome/
      run: |
        dotnet tool install --global dotnet-releaser
        dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml
